- commitments-p256.json
Updates the commitments file for curve p256 to version 2.02 for the CF configuration
> Add EC commitments for version 2.02

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.03 for the CF configuration
> Add EC commitments for version 2.03

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.05 for the CF configuration
> Add EC commitments for version 2.05

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.06 for the CF configuration
> Add EC commitments for version 2.06

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.08 for the CF configuration
> Add EC commitments for version 2.08

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.09 for the CF configuration
> Add EC commitments for version 2.09

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.10 for the CF configuration
> Add EC commitments for version 2.10

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.11 for the CF configuration
> Add EC commitments for version 2.11

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.12 for the CF configuration
> Add EC commitments for version 2.12

- commitments-p256.json
The CF CAPTCHA page has some additional request parameters that should be replicated in the extension request. This patch adds these parameters to the relevant config variables. Tested the patch locally before making the PR. See https://github.com/privacypass/challenge-bypass-extension/blob/master/docs/CONFIG.md for patch documentation.
> Add patch for new CF CAPTCHA

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.14 for the CF configuration
> Add EC commitments for version 2.14

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.15 for the CF configuration
> Add EC commitments for version 2.15

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.16 for the CF configuration
> Add EC commitments for version 2.16

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.18 for the CF configuration
> Add EC commitments for version 2.18

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.19 for the CF configuration
> Add EC commitments for version 2.19

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.20 for the CF configuration
> Add EC commitments for version 2.20

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.21 for the CF configuration
> Add EC commitments for version 2.21

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.22 for the CF configuration
> Add EC commitments for version 2.22

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.23 for the CF configuration
> Add EC commitments for version 2.23

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.24 for the CF configuration
> Add EC commitments for version 2.24

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.25 for the CF configuration
> Add EC commitments for version 2.25

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.26 for the CF configuration
> Add EC commitments for version 2.26

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.27 for the CF configuration
> Add EC commitments for version 2.27

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.28 for the CF configuration
> Add EC commitments for version 2.28

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.29 for the CF configuration
> Add EC commitments for version 2.29

- commitments-p256.json
Updates the commitments file for curve p256 to version 2.30 for the CF configuration
> Add EC commitments for version 2.30

- commitments-p256.json
There was an unsuccessful update of this key.
Reverts privacypass/ec-commitments#70
> Revert "Add EC commitments for version 2.40"
